### ISSUE TITLE
Realms API

### ISSUE THREAD

**Issue by LucienHH** [destruc7i0n/bedrock-dot-dev#17]
Hi There, 

I've been compiling endpoints related to Bedrock Realms and have been roughly documenting them at https://wiki.vg/Bedrock_Realms. Would you be interested in a PR that added this to bedrock.dev, thought I'd ask first before going ahead.

Cheers

**Comment by destruc7i0n** [comment]
Hey,

bedrock.dev is mainly for the generated documentation provided by Mojang. For user-contributed content, there is a community driven [Wiki](https://wiki.bedrock.dev/) on the wiki subdomain that would probably be more fitting. Here is a guide on contributing: https://wiki.bedrock.dev/contribute.html

Thanks

**Comment by LucienHH** [comment]
> Hey,
> 
> bedrock.dev is mainly for the generated documentation provided by Mojang. For user-contributed content, there is a community driven [Wiki](https://wiki.bedrock.dev/) on the wiki subdomain that would probably be more fitting. Here is a guide on contributing: https://wiki.bedrock.dev/contribute.html
> 
> Thanks

Gotcha! I'll close this
