### ISSUE TITLE
Question about demo of Turn-Based RPG 

### ISSUE THREAD

**Issue by SkyleYu** [destruc7i0n/bedrock-dot-dev#30]
https://bedrock.dev/zh/docs/1.17.0.0/1.17.30.23/UI
Hi there,
In this page, you guys mentioned that 'You can check the Turn-Based RPG demo for an example of how to do this.'
But I can't find any demo resource about it in bedrock.dev.
Desperate, I can only contact the edit of page with github, and can only search for help by report issues.
Can you guys show me the link of demo, pls
BTW, if I violated the rule of GitHub Community Guidelines, and post this report at wrong position. Please forgive me, I am rookie in github. Remindme if I violated the rule of GitHub Community Guidelines, i will delete it.

**Comment by MiemieMethod** [comment]
Firstly, this set of docs were auto-generated by source of Minecraft. This Chinese localized page was translated by me and was *just* translated. For *Turn-Based RPG demo*, it was out with Scripting docs so you can find it here: https://bedrock.dev/zh/r/Scripting#Demos . But you know, old Scripting API (including the support for Turn-Based RPG demo) was removed in the latest Minecraft, just a reminding. Finally, if you have found any translation error, please contact me. If you want joining the translation works with me, here can you come: https://github.com/MiemieMethod/addons-docs

**Comment by SirLich** [comment]
Hey @SkyleYu, as Miemie said, bedrock.dev is just a "mirror" for the Microsoft ocs. 

The scripting API is also no longer a thing!

If you want to get more involved, there are a couple of discord servers here, which you may want to join: https://wiki.bedrock.dev/discord.html

**Comment by SkyleYu** [comment]
Thank you guys for helping me solve this problem!! I think I have what I need to develop new mod!
